"""Train development baselines on the current labeled splits."""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.dummy import DummyClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, precision_recall_fscore_support
from sklearn.multiclass import OneVsRestClassifier
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from project.src.data.weak_label_sales_windows import LABEL_COLUMNS, weak_label


def load_split(path: Path) -> tuple[pd.Series, np.ndarray]:
    data = pd.read_csv(path)
    labels = data[LABEL_COLUMNS].astype(int).to_numpy()
    return data["text"], labels


def evaluate(y_true: np.ndarray, y_pred: np.ndarray) -> dict:
    precision, recall, f1, support = precision_recall_fscore_support(
        y_true,
        y_pred,
        average=None,
        zero_division=0,
    )
    per_label = {
        label: {
            "precision": float(precision[index]),
            "recall": float(recall[index]),
            "f1": float(f1[index]),
            "support": int(support[index]),
        }
        for index, label in enumerate(LABEL_COLUMNS)
    }
    return {
        "micro_f1": float(f1_score(y_true, y_pred, average="micro", zero_division=0)),
        "macro_f1": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
        "exact_match_ratio": float(np.all(y_true == y_pred, axis=1).mean()),
        "per_label": per_label,
    }


def fit_predict_majority(
    train_x: pd.Series,
    train_y: np.ndarray,
    test_x: pd.Series,
) -> np.ndarray:
    predictions = []
    for label_index in range(train_y.shape[1]):
        classifier = DummyClassifier(strategy="most_frequent")
        classifier.fit(train_x, train_y[:, label_index])
        predictions.append(classifier.predict(test_x))
    return np.vstack(predictions).T


def fit_predict_tfidf_logreg(
    train_x: pd.Series,
    train_y: np.ndarray,
    test_x: pd.Series,
) -> np.ndarray:
    classifier = Pipeline(
        steps=[
            ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=2, max_features=20000)),
            (
                "clf",
                OneVsRestClassifier(
                    LogisticRegression(max_iter=1000, class_weight="balanced")
                ),
            ),
        ]
    )
    classifier.fit(train_x, train_y)
    return classifier.predict(test_x)


def fit_predict_tfidf_linear_svm(
    train_x: pd.Series,
    train_y: np.ndarray,
    test_x: pd.Series,
) -> np.ndarray:
    classifier = Pipeline(
        steps=[
            ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=2, max_features=20000)),
            (
                "clf",
                OneVsRestClassifier(LinearSVC(class_weight="balanced")),
            ),
        ]
    )
    classifier.fit(train_x, train_y)
    return classifier.predict(test_x)


def predict_rule_weak_labeler(texts: pd.Series) -> np.ndarray:
    rows = []
    for text in texts:
        labels = weak_label(text)
        rows.append([int(labels[label]) for label in LABEL_COLUMNS])
    return np.asarray(rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--splits-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--predictions-output", type=Path)
    args = parser.parse_args()

    train_x, train_y = load_split(args.splits_dir / "train.csv")
    validation_x, validation_y = load_split(args.splits_dir / "validation.csv")
    test_x, test_y = load_split(args.splits_dir / "test.csv")

    models = {
        "majority": fit_predict_majority,
        "tfidf_logreg": fit_predict_tfidf_logreg,
        "tfidf_linear_svm": fit_predict_tfidf_linear_svm,
    }

    results = {
        "warning": (
            "Development results on weak labels. The rule_weak_labeler baseline "
            "is circular because the current labels were generated by the same "
            "rule family. Recompute final metrics on manually validated labels."
        ),
        "validation": {},
        "test": {},
    }
    test_predictions: dict[str, np.ndarray] = {}

    for name, predict_fn in models.items():
        validation_pred = predict_fn(train_x, train_y, validation_x)
        test_pred = predict_fn(train_x, train_y, test_x)
        test_predictions[name] = test_pred
        results["validation"][name] = evaluate(validation_y, validation_pred)
        results["test"][name] = evaluate(test_y, test_pred)

    validation_rule = predict_rule_weak_labeler(validation_x)
    test_rule = predict_rule_weak_labeler(test_x)
    test_predictions["rule_weak_labeler"] = test_rule
    results["validation"]["rule_weak_labeler_circular"] = evaluate(
        validation_y, validation_rule
    )
    results["test"]["rule_weak_labeler_circular"] = evaluate(test_y, test_rule)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(results, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    if args.predictions_output:
        test_data = pd.read_csv(args.splits_dir / "test.csv", encoding="utf-8-sig")
        rows = []
        for row_index, row in test_data.iterrows():
            output_row = {
                "id": row["id"],
                "dialogue_id": row["dialogue_id"],
                "text": row["text"],
            }
            for label_index, label in enumerate(LABEL_COLUMNS):
                output_row[f"gold_{label}"] = int(test_y[row_index, label_index])
            for model_name, predictions in test_predictions.items():
                for label_index, label in enumerate(LABEL_COLUMNS):
                    output_row[f"{model_name}_{label}"] = int(
                        predictions[row_index, label_index]
                    )
            rows.append(output_row)

        args.predictions_output.parent.mkdir(parents=True, exist_ok=True)
        with args.predictions_output.open("w", newline="", encoding="utf-8") as target:
            writer = csv.DictWriter(target, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)

    print(f"output={args.output}")
    if args.predictions_output:
        print(f"predictions_output={args.predictions_output}")
    for split_name in ("validation", "test"):
        print(split_name)
        for model_name, metrics in results[split_name].items():
            print(
                f"  {model_name}: "
                f"micro_f1={metrics['micro_f1']:.3f} "
                f"macro_f1={metrics['macro_f1']:.3f} "
                f"exact={metrics['exact_match_ratio']:.3f}"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
